### ISSUE TITLE
linux problem

### ISSUE THREAD

**Issue by afsharsafavi** [cfpp2p/transmission#10]
Hello
Can you build linux version for latest release.
I can't use latest release on centos.
I should use transmissiondcfp-2.77plus14734-14.tar.bz2 from previous release.

**Comment by cfpp2p** [comment]
@afsharsafavi 
14734-14-**2** release is maintenance for included released windows binary  _transmission remote GUI_.

14734-14-2 daemon built will be**_identical_** to that of 14734-14. There are zero changes to actual daemon 14734-14-2 source, it's just the NEWS file that was changed. 14734-14-2 builds without issue for me.

> I can't use latest release on centos.

Please elaborate.

**Comment by afsharsafavi** [comment]
Ok.
Thanks a lot
