### ISSUE TITLE
Too many open files problem

### ISSUE THREAD

**Issue by afsharsafavi** [cfpp2p/transmission#11]
Hello
Sometime I received this error from web daemon.
"404: Not Found
/usr/local/share/transmission/web/index.html (Too many open files)"
I decreased number of peers but nothing changed and every time I should restart daemon.
I used latest release.

**Comment by cfpp2p** [comment]
@afsharsafavi 
cURL has open file limit of 1024. This is an ongoing problem with **all** versions of transmission. I have put a work-around for "_Unable to save resume file: Too many open files_" https://github.com/cfpp2p/transmission/blob/svn/trunk/libtransmission/resume.c#L730

I'm not fluent with centos. Does something like https://www.cyberciti.biz/faq/linux-unix-nginx-too-many-open-files/ help with error
 _"404: Not Found /usr/local/share/transmission/web/index.html (Too many open files)_" ?

**Comment by afsharsafavi** [comment]
Hello
Thanks for your reply.
I did that changes and I think that I should wait some days to check problem will be occur again or not.
(I think your link will be help)
Thanks for your support.

**Comment by afsharsafavi** [comment]
Problem come back.
I have lot of error :
transmission-daemon[26496]: Couldn't create socket: Too many open files (fdlimit.c:701)

**Comment by cfpp2p** [comment]
@afsharsafavi
This **is** the cURL open files limit of 1024 affecting _all_ versions of transmission. Reducing your global peer limit to 800 or less could help ( http://web.archive.org/web/20151008220607/https://trac.transmissionbt.com/ticket/5306 **see comment # 3** ) [ TRAC is down - https://github.com/transmission/transmission/issues/703 so resorting to web archive **.**org ].

This is a long standing cURL limitation affecting transmission past and present: https://github.com/transmission/transmission/issues/633

You'll see lots of posts pertaining to this issue.
i.e.
http://web.archive.org/web/20151013224000/https://trac.transmissionbt.com/ticket/5056
http://web.archive.org/web/20151025130232/https://trac.transmissionbt.com/ticket/5161
http://web.archive.org/web/20151008220607/https://trac.transmissionbt.com/ticket/5306
http://web.archive.org/web/20151016152554/https://trac.transmissionbt.com/ticket/5898
https://forum.transmissionbt.com/viewtopic.php?f=1&t=14073
https://forum.transmissionbt.com/viewtopic.php?f=1&t=17820
https://forum.transmissionbt.com/viewtopic.php?f=4&t=17826

Set global peer limit 800 or less. Try That.

**Comment by cfpp2p** [comment]
@afsharsafavi
This **is** the cURL open files limit of 1024 affecting _all_ versions of transmission. Reducing your global peer limit to 800 or less could help ( http://web.archive.org/web/20151008220607/https://trac.transmissionbt.com/ticket/5306 **see comment # 3** )
TRAC is down https://github.com/transmission/transmission/issues/703 so resorting to web archive **.**org

This is a long standing cURL limitation affecting transmission past and present: https://github.com/transmission/transmission/issues/633

You'll see lots of posts pertaining to this issue.
i.e.
http://web.archive.org/web/20151013224000/https://trac.transmissionbt.com/ticket/5056
http://web.archive.org/web/20151025130232/https://trac.transmissionbt.com/ticket/5161
http://web.archive.org/web/20151008220607/https://trac.transmissionbt.com/ticket/5306
http://web.archive.org/web/20151016152554/https://trac.transmissionbt.com/ticket/5898
https://forum.transmissionbt.com/viewtopic.php?f=1&t=14073
https://forum.transmissionbt.com/viewtopic.php?f=1&t=17820
https://forum.transmissionbt.com/viewtopic.php?f=4&t=17826

Set global peer limit 800 or less. Try That.

**Comment by afsharsafavi** [comment]
Global peer limit was set to 250 when this problem happened.

**Comment by cfpp2p** [comment]
There is no proper solution to this problem. Reduce the number of torrents and/or reducing global peer limits. Maybe something written up in one of the numerous posts you'll find by searching _transmission too many open files_. Sorry I can't be of more help...

**Comment by cfpp2p** [comment]
@afsharsafavi

> Disabling threads and enabling ares for curl resolves the issue.. great, thanks!

http://web.archive.org/web/20151123152018/https://trac.transmissionbt.com/ticket/3504  ?
