### ISSUE TITLE
Solution for trackers that ban pre-2.94 versions of Transmission

### ISSUE THREAD

**Issue by ghost** [cfpp2p/transmission#12]
A few trackers have banned pre-2.94 versions of Transmission because of the malware injection drama Transmission had a couple years back and an SSL security issue in pre-2.94 versions. Basically, I can't use any versions of Transmission older than 2.94 on those trackers, which rules out using transmission-daemon because it is based on 2.77.  

I realize this issue doesn't affect many people, but will there ever be an upcoming version of transmission-daemon that is based on the very latest version, or am I stuck using the official 2.94 Windows version for all my torrents? 

Any chance of the upcoming 3.0 version becoming the next base for transmission-daemon?

**Comment by cfpp2p** [comment]
https://sourceforge.net/p/transmissiondaemon/discussion/general/thread/beb7dfad/

**Comment by ghost** [comment]
@cfpp2p Thanks for the solution. I'll close this. Thanks for the work on this daemon. This is the best torrent client for Windows I've found so far.
