### ISSUE TITLE
Location of the main resource.

### ISSUE THREAD

**Issue by iZeus83** [cfpp2p/transmission#5]
Hi,

It seems if I try to compile and build "transmission-remote-GUI" for windows then I see that version is old from 2011.

Please where I can get the latest source?. thanks.

**Comment by cfpp2p** [comment]
I have already provided compiled binary (.exe)
https://github.com/cfpp2p/transmission/archive/Windows_Daemon_&_Clients.zip
UNZIP -- `transmission-Windows_Daemon_-_Clients.zip`
use _transguiPortable_ or transgui.exe `\transmission-Windows_Daemon_-_Clients\WINdows_GUI\`
Or here: http://sourceforge.net/projects/transmissiondaemon/files/

If you still want to compile yourself.
I haven't updated the original _history.txt_
That's maybe why you're seeing Apr 09, 2011 ?
Most recent update:
Jul 4, 2015     https://github.com/cfpp2p/transmission/commit/162401b38126a412d082d8f5044545e417c93fea

Next two oldest:
Jul 31, 2014    https://github.com/cfpp2p/transmission/commit/b3ce2eb9488f79cb07074e97ab925ce8e05c0861
Mar 26, 2014    https://github.com/cfpp2p/transmission/commit/2ada37461dc99ac6152f1942898464bc86f3b896

Follow instructions here: https://github.com/cfpp2p/transmission/wiki/Compile-enhanced--remote-GUI

https://github.com/cfpp2p/transmission/archive/Windows_Daemon_&_Clients.zip
UNZIP -- `transmission-Windows_Daemon_-_Clients.zip`
source from the unzipped -- `\transmission-Windows_Daemon_-_Clients\WINdows_GUI\source\`

Alternate source: http://transmissionbt.net/enhanced-tr_GUI-source.zip

**Comment by iZeus83** [comment]
Hi, thank you for your attention.

Yep, I use and get only "transgui.exe" that show this in about window.

![image](https://cloud.githubusercontent.com/assets/8102136/10855538/70f6726e-7f42-11e5-9430-a8b873b11316.png)

So, this windows it's fake because the last update it's from July 4 2015.

**Comment by cfpp2p** [comment]
I keep it up to date so don't worry about what shows in that window. It shows the last time the version I maintain was updated by the official maintainer's source I began with. It's not an issue.

**Comment by iZeus83** [comment]
ok, thanks for all :)
