### ISSUE TITLE
[compile error] recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by pyed** [cfpp2p/transmission#6]
I'm hitting this error after issuing `make`
here's how I'm doing it: http://sprunge.us/bVhT

**Comment by cfpp2p** [comment]
if you just download https://github.com/cfpp2p/transmission/archive/svn/trunk.zip and compile the source instead of git clone does that work for you?

**Comment by pyed** [comment]
I see where the problem is, there's a problem with some files permissions, for some reason some scripts aren't given the right permission to allow execution:
`chmod +x autogen.sh update-version-h.sh third-party/miniupnp/updateminiupnpcstrings.sh`

after issuing that command before executing `./autogen.sh` I was able to `make` it. it worked for `trunk.zip` as well as `git clone`
