### ISSUE TITLE
"prefetch counter corrupt" while seeding

### ISSUE THREAD

**Issue by ryzhovau** [cfpp2p/transmission#7]
After few minutes of seeding I get following error:
```
[20:53:02.188] xyz.iso prefetch counter corrupt! prefetchCount value is 0 . Upload failed. (torrent.c:536)
```
Reproduced on any torrent.

* source code e0a750c9184209ff558d9eccabb845c6feb6e0c2,
* some [patches](https://github.com/Entware-ng/graveyard/tree/master/transmission-cfp/patches) applied,
* MIPSEL toolchain based on k2.6.22, GCC 5.4.0, uClibc-ng 1.0.17,
* target system where error appeared is MIPS router with 64MB RAM, k3.4.113, Ext4 partition.

[Here](https://gist.github.com/ryzhovau/6bf91e2f4b802cc4eed1d41baa854a5b) is a build log.

**Comment by cfpp2p** [comment]
Please corroborate https://github.com/cfpp2p/transmission/commit/8e73c16a1801589c08df72029d18a609196788eb fixes the issue.

**Comment by ryzhovau** [comment]
No issues after few hours of seeding.
