### ISSUE TITLE
Cannot compile in Linux (Debian 9)

### ISSUE THREAD

**Issue by webwarrior-ws** [cfpp2p/transmission#8]
When executing `make`:

```
crypto.c: In function ‘ensureKeyExists’:
crypto.c:102:11: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
         dh->p = BN_bin2bn( dh_P, sizeof( dh_P ), NULL );
           ^~
```

**Comment by cfpp2p** [comment]
@webwarrior-ws   I've committed  https://github.com/cfpp2p/transmission/commit/26e6880747c71a5e8e7fc5b2844e5ff503be1ad2 for this issue. Could you test and report back. Thanks!

**Comment by cfpp2p** [comment]
@webwarrior-ws  https://github.com/cfpp2p/transmission/commit/a8a0b40c2208d7556c02727b29d35b2e67f51a06 Please let me know how everything works now with this additional commit.

**Comment by webwarrior-ws** [comment]
Now I'm having problems building from git:

When I run `autogen.sh`:
`config.status: error: cannot find input file: 'po/Makefile.in.in'`

When trying to run `intltoolize`:
`ERROR: 'IT_PROG_INTLTOOL' must appear in configure.ac for intltool to work.`

**Comment by cfpp2p** [comment]
@webwarrior-ws 

**po/Makefile.in.in is missing**
https://github.com/cfpp2p/transmission/issues/1#issuecomment-129141064
and
**svn repository building:**
**re-generate Makefile.in.in:**
https://github.com/cfpp2p/transmission/issues/1#issuecomment-129548676
and
 **I wasn't aware of the intltoolize command**
https://github.com/cfpp2p/transmission/issues/1#issuecomment-129575933

https://github.com/V-E-O/transmission/commit/e07bd4451864c9aeead0d2e72ea7c0230fa8ad96#commitcomment-22770385

**Comment by webwarrior-ws** [comment]
OK, Makefile.in.in from V-E-O worked.
I even got it compiled (had to install zlib1g-dev thought, which is not listed in dependencies for Debian).

But after I installed it using chekinstall, transmission-daemon no longer starts.

```
# systemctl status transmission-daemon
● transmission-daemon.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead) since Thu 2017-07-06 21:31:36 EEST; 1min 16s ago
 Main PID: 2159 (code=exited, status=0/SUCCESS)
```

Unmasking the service doesn't work either - status will change to `active (exited)`

**Comment by cfpp2p** [comment]
@webwarrior-ws    Can you start the daemon from the terminal?

I think transmission-daemon service is try to start using some default startup script and you don't want that. Try startup script as here: https://trac.transmissionbt.com/wiki/Scripts/initd

I don't have much experience with Debian. Searching the forums  might help i.e.
https://forum.transmissionbt.com/search.php?keywords=Debian+start+up+script
https://forum.transmissionbt.com/search.php?keywords=Debian+start-up+script
https://forum.transmissionbt.com/search.php?keywords=Debian+startup+script
https://forum.transmissionbt.com/index.php

My opinion is that the startup/bootscript from the package manager of Debian is for a different transmission version so for compiled version so you'll need to change that.

I'll try to help but in the Debian area I lack expertise.

### EDIT:
**_add user transmission and make an initd script_**
https://forum.transmissionbt.com/viewtopic.php?f=1&t=16887
Might help...

**Comment by cfpp2p** [comment]
@webwarrior-ws   https://forum.transmissionbt.com/viewtopic.php?f=1&t=16887   The concepts there should work and the initd script is the same as https://trac.transmissionbt.com/wiki/Scripts/initd which by its [history](https://trac.transmissionbt.com/wiki/Scripts/initd?action=history) functions for transmissions versions since https://trac.transmissionbt.com/ticket/4724

Also note [Building from trunk throws error on po Makefile (Debian)](https://trac.transmissionbt.com/ticket/4722#comment:2) , [Bug in r1558 (po/Makefile.in.in)](https://trac.transmissionbt.com/ticket/3123#comment:1) and [debian build: error: cannot find input file: `po/Makefile.i](https://forum.transmissionbt.com/viewtopic.php?f=1&t=12693#p58507)

**Comment by webwarrior-ws** [comment]
Thanks @cfpp2p, I finally got it working.

Script from https://forum.transmissionbt.com/viewtopic.php?f=1&t=16887 should probably be mentioned in wiki here: https://github.com/transmission/transmission/wiki/Building-Transmission.

Only things that are different from default Debian package are transmission user name (`transmission-debian`) and location of config file (`/etc/transmission-daemon`). These matter only if transitioning from official Debian package though.

**Comment by cfpp2p** [comment]
@ggandycong 

https://github.com/transmission/transmission/issues  your issue number 801

>There is no po/Makefile.in.in file in po directory after running autoreconf -i command,I don't know when the po/Makefile.in.in file is generated, why not generate this file, that may be the problem.

 Jul 6, 2017 issuecomment-313449168  --> five comments above
https://github.com/cfpp2p/transmission/issues/8#issuecomment-313449168

**Comment by cfpp2p** [comment]
>po/Makefile.in.in is missing

I also include po/Makefile.in.in in  releases
https://github.com/cfpp2p/transmission/releases
https://github.com/cfpp2p/transmission/releases/download/2.77plus14734-14-2/poMakefile-inin.zip
